[package]
name = "calq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.4.3"
chumsky = "0.9.3"
color-eyre = "0.6.3"
num-rational = "0.4.1"
rustyline = "14.0.0"
